name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 1.0.0
homepage: https://github.com/frencojobs/envify

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  build: ^1.5.0
  envify: ^1.0.1
  dotenv: ^2.0.0
  analyzer: ^0.40.4
  source_gen: ^0.9.7+1

dev_dependencies:
  test: ^1.6.0
  lint: ^1.3.0
  source_gen_test: ^0.1.1+1

scripts: ../derry.yaml
