name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 1.1.0
homepage: https://github.com/frencojobs/envify

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  analyzer: ^0.40.4
  build: ^1.5.0
  dotenv: ^2.0.0
  envify: ^2.0.0
  path: ^1.8.0-nullsafety.3
  source_gen: ^0.9.7+1

dev_dependencies:
  lint: ^1.5.1
  source_gen_test: ^0.1.1+1
  test: ^1.16.0-nullsafety.12

scripts: ../derry.yaml
