name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 1.1.0
homepage: https://github.com/frencojobs/envify

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  dotenv: ^3.0.0-nullsafety.0
  envify: ^2.0.0
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  lint: ^1.5.1
  source_gen_test: ^1.0.0
  test: ^1.16.8

scripts: ../derry.yaml
